### PR TITLE
TS-363 Notifications API

### PR DESCRIPTION
**Pull request by rileykc98**
API for notifications. Due to some poor version control on my part, this includes some work on notifications preferences API as well, but I was not able to complete that for this sprint.

### CODE REVIEW

**Comment by itsShaVawn** [comment]
You'll need to fix those 20 code smells. Most of them are because you are using objects instead of primitive types. And also fix that bug by just placing console.logs or something in the meantime

**Comment by kennguyen0303** [comment]
@rileykc98 `string` instead of `String` to remove the code smell. You have one bug for creating a if-else but don't do anything within both blocks.

**Review by itsShaVawn — APPROVED** [review]
Nice!

**Review by GadoliniumPotassium — APPROVED** [review]
Good job, clear concise and it works

**Pull request merged**
